import { GoalTemplate } from "@/types";

export const GOAL_TEMPLATES: GoalTemplate[] = [
  {
    id: "tpl-custom",
    title: "Custom Goal",
    description: "Start from a blank slate and define your own unique goal.",
    emoji: "✍️",
    category: "General",
    priority: "medium",
    cadence: "one_time",
  },
  {
    id: "tpl-startup-launch",
    title: "Launch MVP",
    description: "Get the first version of our product live and in the hands of users.",
    emoji: "🚀",
    category: "Startup",
    priority: "high",
    cadence: "one_time",
  },
  {
    id: "tpl-student-study",
    title: "Weekly Study Group",
    description: "Meet up with the study group and cover the week's curriculum.",
    emoji: "📚",
    category: "Education",
    priority: "medium",
    cadence: "weekly",
  },
  {
    id: "tpl-church-attendance",
    title: "Monthly Outreach Event",
    description: "Host a community outreach event or gathering every month.",
    emoji: "🕊️",
    category: "Community",
    priority: "high",
    cadence: "monthly",
  },
  {
    id: "tpl-friends-trip",
    title: "Save for Group Trip",
    description: "Everyone deposits their share into the joint trip fund.",
    emoji: "✈️",
    category: "Personal",
    priority: "medium",
    cadence: "monthly",
    targetNumber: 500,
    unit: "$",
  },
  {
    id: "tpl-biz-sales",
    title: "10 New Sales Calls",
    description: "Reach out and speak to 10 potential new customers.",
    emoji: "📞",
    category: "Business",
    priority: "high",
    cadence: "weekly",
    targetNumber: 10,
    unit: "calls",
  },
  {
    id: "tpl-fitness-challenge",
    title: "Daily Workout",
    description: "Complete a 30-minute workout or physical activity.",
    emoji: "🏃",
    category: "Health",
    priority: "medium",
    cadence: "daily",
  },
  {
    id: "tpl-one-time-project",
    title: "Project Milestone",
    description: "A major project phase or one-off deliverable.",
    emoji: "🏁",
    category: "Operations",
    priority: "medium",
    cadence: "one_time",
  },
  {
    id: "tpl-daily-reading",
    title: "Daily Reading",
    description: "Stay consistent with your daily reading, whether it's scripture, a book, or an article.",
    emoji: "📖",
    category: "Growth",
    priority: "medium",
    cadence: "daily",
  },
  {
    id: "tpl-daily-content",
    title: "Daily Content Post",
    description: "Post a piece of content on social media to build your audience and stay active.",
    emoji: "📱",
    category: "Marketing",
    priority: "medium",
    cadence: "daily",
  },
];
