project_id = "jnoqlbqilwohfyfudnss"

[functions.flutterwave-payment]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-email-resend]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-trial-reminder]
verify_jwt = false
